apiVersion: v1
kind: Secret
metadata:
  name: compute-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.compute.username | b64enc }}
  password: {{ .Values.compute.password | b64enc }}