{{- if .Values.job.pull_secret_dockerconfigjson }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.job.pull_secret_dockerconfigjson }}
kind: Secret
metadata:
  name: {{ .Values.job.image_pull_secret }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
{{- end}}