apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: twistlock-updater-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: twistlock-updater-service
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: twistlock-updater-role
  apiGroup: rbac.authorization.k8s.io
