apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: twistlock-updater-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
{{- if eq .Values.defender.orchestrator "openshift" }}
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"] # Allow Create SecurityContextConstraints
  verbs: ["create", "delete"]
{{- end}}
{{- if or .Values.defender.monitor_istio .Values.defender.monitor_service_accounts .Values.defender.collect_pod_labels }}
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"] # Allow Defenders to list RBAC resources
  verbs: ["create", "delete"]
{{- if .Values.defender.monitor_service_accounts }}
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"] # Allow Defenders to list RBAC resources
  verbs: ["list"]
{{- end}}
{{- if .Values.defender.monitor_istio }}
- apiGroups: ["security.istio.io"]
  resources: ["authorizationpolicies", "peerauthentications"] # Allow Defenders to list Istio security resources
  verbs: ["list"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices", "destinationrules", "gateways"] # Allow Defenders to list Istio networking resources
  verbs: ["list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "endpoints", "services"] # Allow Defenders to list pods, services and endpoints
  verbs: ["list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/proxy"] # Allow Defenders to get pod proxy
  verbs: ["get"]
{{- end}}
{{- if .Values.defender.collect_pod_labels }}
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"] # Allow Defenders to get Deployments and ReplicaSets
  verbs: ["get"]
- apiGroups: [""] # Core API
  resources: ["namespaces", "pods"] # Allow Defenders to get Namespaces and Pods
  verbs: ["get"]
{{- end}}
{{- end}}
