{{- if and .Values.compute.secret_store.name .Values.compute.secret_store.remote_key }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.compute.secret }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.compute.secret_store.refresh_interval }}
  secretStoreRef:
    name: {{ .Values.compute.secret_store.name }}
    kind: {{ .Values.compute.secret_store.kind }}
  target:
    name: {{ .Values.compute.secret }}
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: {{ .Values.compute.secret_store.remote_key }}
      property: PRISMA_USERNAME
  - secretKey: password
    remoteRef:
      key: {{ .Values.compute.secret_store.remote_key }}
      property: PRISMA_PASSWORD
  - secretKey: compute_api_endpoint
    remoteRef:
      key: {{ .Values.compute.secret_store.remote_key }}
      property: COMPUTE_API_ENDPOINT

{{- else if and .Values.compute.username .Values.compute.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.compute.secret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.compute.username | b64enc }}
  password: {{ .Values.compute.password | b64enc }}
  compute_api_endpoint: {{ .Values.compute.api_endpoint | b64enc }}
{{- end }}