{{- if and .Values.compute.username .Values.compute.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.compute.secret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.compute.username | b64enc }}
  password: {{ .Values.compute.password | b64enc }}
{{- end }}