kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: twistlock-updater-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.job.storage.access_mode }}
  resources:
    requests:
      storage: {{ .Values.job.storage.size }}
  {{- if .Values.job.storage.class_name }}
  storageClassName: {{ .Values.job.storage.class_name }}
  {{- end }}
  {{- if .Values.job.storage.volume_name }}
  volumeName: {{ .Values.job.storage.volume_name }}
  {{- end }}