apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: twistlock-updater-role
  namespace: {{ .Release.Namespace }}
rules: 
- apiGroups:
  - "apps"
  resources:
  - "daemonsets"
  verbs: 
  - "list"
  - "create"
  - "delete"
- apiGroups: 
  - ""
  - "apps"
  - "rbac.authorization.k8s.io"
  resources: 
  - "secrets"
  - "serviceaccounts"
  - "services"
  verbs: 
  - "create"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "list"
- apiGroups:
  - ""
  resources:
  - "pods/log"
  verbs:
  - "get"