apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: twistlock-updater-role
  namespace: {{ .Release.Namespace }}
rules: 
- apiGroups:
  - "apps"
  resources:
  - "daemonsets"
  verbs: 
  - "create"
- apiGroups:
  - "apps"
  resources:
  - "daemonsets"
  resourceNames:
  - twistlock-defender-ds
  verbs: 
  - "get"
  - "delete"
- apiGroups: 
  - ""
  - "apps"
  - "rbac.authorization.k8s.io"
  resources: 
  - "secrets"
  - "serviceaccounts"
  - "services"
  verbs:
  - "create"
- apiGroups: 
  - ""
  - "apps"
  - "rbac.authorization.k8s.io"
  resources: 
  - "secrets"
  - "serviceaccounts"
  - "services"
  resourceNames:
  - twistlock-secrets
  - twistlock-service
  - defender
  verbs:
  - "get"
  - "delete"
