apiVersion: v1
kind: ServiceAccount # Service Account is used for managing security context constraints policies in Openshift (SCC)
metadata:
  name: {{ .Values.job.service_account.name }}
  namespace: {{ .Release.Namespace }}
{{- if or .Values.job.role_arn .Values.job.service_account.annotations }}
  annotations:
  {{- if .Values.job.role_arn }}
    eks.amazonaws.com/role-arn: {{ .Values.job.role_arn }}
  {{- end}}
  {{- if .Values.job.service_account.annotations }}
  {{- range $key, $val := .Values.job.service_account.annotations }}
    {{ $key }}: {{ $val }}
  {{- end}}
  {{- end}}
{{- end}}