apiVersion: v1
kind: ServiceAccount # Service Account is used for managing security context constraints policies in Openshift (SCC)
metadata:
  name: twistlock-updater-service
  namespace: {{ .Release.Namespace }}
{{- if .Values.job.role_arn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.job.role_arn }}
{{- end}}
