compute:
  api_endpoint: 
  username: 
  password: 
  skip_verify: false
 
job:
  schedule: "0 0 * * Sun"
  timezone: "Etc/UTC" #Refer to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones to get your current time zone
  image_name: 
  image_pull_secret: 
  pull_secret_dockerconfigjson: 
  role_arn:
  cluster_role_name: twistlock-updater-clusterrole
  storage:
    access_mode: ReadWriteOnce
    size: 1Gi
    class_name: default
  debug: false
  init_configmap: 
  annotations:

defender:
  console_name: ""
  communication_port: ""
  orchestrator: kubernetes
  container_runtime: containerd
  collect_pod_labels: false
  monitor_service_accounts: false
  cluster_name: ""
  runtime_socket_path: ""
  node_selector: ''
  role_arn: "" 
  unique_hostname: false 
  monitor_istio: false
  bottlerocket: false
  gke_autopilot: false
  talos: false
  image_name: ""
  image_pull_secret: ""
  selinux: false
  privileged: false
  cpu_limit: 0
  memory_limit: 0
  priority_class_name: ""
  project_id: ""
  region: ""
  proxy:
    ca:
    httpProxy:
    noProxy:
    password:
    user:
  tolerations:
#  - effect: NoSchedule 
#    key: key1
#    operator: Exists
#    toleration_seconds: 0
#  - effect: NoExecute 
#    key: key1
#    operator: Equals
#    toleration_seconds: 0
#    value: value1
  annotations:
#    annotation1: test



